### ISSUE TITLE
ReadUntil(terminators) allocations

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#107]
https://github.com/ValveResourceFormat/ValveKeyValue/blob/29a24e8ec79e6179dc6f8220b9d41f1b42d6414b/ValveKeyValue/ValveKeyValue/Deserialization/KeyValues1/KV1TokenReader.cs#L141

a HashSet is created every time, and the incoming parameter whenever its an array.

Should we update to .NET8 and use SearchValues?

**Comment by yaakov-h** [comment]
SearchValues does sound good 😄
