### ISSUE TITLE
Not all escape sequences are implemented

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#32]
See the list here:
https://github.com/ValveSoftware/GameNetworkingSockets/blob/8348e9234aba1b034f51ceff406a715de9ef61ad/src/tier1/utlbuffer.cpp#L54

The only strange thing to me here is `\?`.

**Comment by yaakov-h** [comment]
`\?` seems to be a trigraph oddity: https://stackoverflow.com/a/18156263/1994390
