### ISSUE TITLE
Support the '=' as an assignment (CS:GO)

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#33]
I was looking at the leaked CS:GO code, they added the following:

```
		// support the '=' as an assignment, makes multiple-keys-on-one-line easier to read in a keyvalues file
		if ( *value == '=' && !wasQuoted )
		{
```

**Comment by yaakov-h** [comment]
Any idea what this looks like in text?

**Comment by xPaw** [comment]
https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/cfg/survival/survival_config.kv3

Could be this.

**Comment by xPaw** [comment]
don't think we need this
