### ISSUE TITLE
Casting to DateTime is not supported

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#63]
There's this:
https://github.com/SteamDatabase/ValveKeyValue/blob/225ef38dca38bb83aefe3c43c65822d64c85b01c/ValveKeyValue/ValveKeyValue/KVObjectValue.cs#L44-L47

However `TryConvertValueTo` listed it as a supported conversion:
https://github.com/SteamDatabase/ValveKeyValue/blob/dfb96b52087fbd4f27e4128a5368cf318a04412b/ValveKeyValue/ValveKeyValue/ObjectCopier.cs#L407

I commented that out for now, was it simply never finished?

**Comment by yaakov-h** [comment]
I think it was there because IConvertible officially supports DateTime, but we never implemented it as there's no strict definition of what a KV DateTime looks like - could be a string with a million formats, or unix time integer, or perhaps even valve time integer (GID_t epoch).

**Comment by xPaw** [comment]
So removing it from `TryConvertValueTo` should be correct then.

**Comment by yaakov-h** [comment]
I think so, but you'll just get a `NotSupportedException` instead. Which is probably the correct exception here.

**Comment by xPaw** [comment]
You do, which is more helpful due to a better exception message: eb5d13f301d1487836702070c36fb77b95a5a3ec
