### ISSUE TITLE
Fails to serialize `ValueTuple`

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#79]
This line throws `System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'`
https://github.com/SteamDatabase/ValveKeyValue/blob/ed10cc104681d33935fc2b7ea3d6701970a581f5/ValveKeyValue/ValveKeyValue/PropertyMember.cs#L29

```csharp
public class Test
{
    public List<(string a, string b)> Something { get; } = new()
    {
        ( "hello", "world" )
    };
}

using var ms = new MemoryStream();
KVSerializer.Create(KVSerializationFormat.KeyValues1Text).Serialize(ms, new Test(), "Test");
Encoding.UTF8.GetString(ms.ToArray());
```

**Comment by yaakov-h** [comment]
What should this look like? Should this simply be:

```plain
    "Item1" "hello"
    "Item2" "world"
```
?

The names `a` and `b` are not necessarily available at runtime IIRC, but I can have a look to see if we can fetch them out of metadata.

**Comment by xPaw** [comment]
That's a good question actually, but if we assume that tuples and records are similar to classes, then what you propose is fine.

**Comment by yaakov-h** [comment]
no, that would be very weird to then try handle for 1-arity or 3-arity value tuples, or more.
