### ISSUE TITLE
Booleans are serialized as empty objects

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveKeyValue#81]
```
public bool Test { get; set; }
```

output:
```
"Test"
{
}
```

**Comment by xPaw** [comment]
This also happens to byte arrays:

```
				"UnknownBits"
				{
					"0"
					{
					}
					"1"
					{
					}
```

**Comment by yaakov-h** [comment]
What should they be serialised as? `"true"`/`"false"`, or `"1"`/`"0"`?

**Comment by xPaw** [comment]
Anything is gonna be better than the current output (and I suppose ideally if it can parse back to strongly typed object as a bool).

**Comment by yaakov-h** [comment]
```cpp
void SetBool( const char *keyName, bool value ) { SetInt( keyName, value ? 1 : 0 ); }
```
```cpp
bool KeyValues::GetBool( const char *keyName, bool defaultValue )
{
	if ( FindKey( keyName ) )
		return 0 != GetInt( keyName, 0 );

	return defaultValue;
}
```

Valve are using ints, seems easy enough. It's not entirely symmetric, but ¯\\\_(ツ)\_/¯

**Comment by xPaw** [comment]
> It's not entirely symmetric

Parsing to a typed object should hopefully work.
